### PR TITLE
new rule: Valid by tagname

### LINKED ISSUE #59: Rule Proposal: warn if tag name values are incorrect
Sample use case: http://stackoverflow.com/questions/40881822/cannnot-focus-element-in-dropdown-test

Example of a violation:

```js
element(by.tagName('option[value="Test"]'))
```

Here, a CSS selector is used as a tag name locator value.

### PR DESCRIPTION
**Pull request by eLRuLL**
fixes #59 

@alecxe what do you think? Should this be more permissive? is it ok to list all HTML tags?

### CODE REVIEW

**Comment by alecxe** [comment]
Hey @eLRuLL. Thanks for the PR, let's work on this.

Couple things: 

 1. I think we should not list all the possible tag names and should come up with a general rule/regexp for a tag name?
 2. In the rule documentation page, did you mix up the "good" and "bad" examples at the bottom? :)

**Comment by eLRuLL** [comment]
@alecxe :

1. Yeah I agree, but I don't think we could make sure the HTML tags listed here are the only ones being used. I think we could even come up with a way to tell the developer which specific `by.*` locator to use, but that rule should apply to every locator, so for example if someone is putting a `css` expression but using `by.xpath`, it should recommend use `by.css`.

2. Sorry, I did it again :( I am fixing it now.

**Comment by alecxe** [comment]
@eLRuLL thanks for the documentation fix.

I like your idea to have locator-specific checks, but let's discuss it separately. For this particular issue, let's just apply the [general HTML tag name](https://www.w3.org/TR/html/syntax.html#tag-name) requirements checks, similar to how we've done it for the `id` attribute in `valid-by-id`. Thanks!

**Comment by eLRuLL** [comment]
no feeling is better than that simple email with "Merged" on it 😄

**Pull request merged**
